-- Insert basic workout names
INSERT INTO workout_names VALUES
        ('Starting Strength A', 'strength'),
        ('Starting Strength B', 'strength'),
        ('Whole Body 1', 'strength'),
        ('Whole Body 2', 'strength'),
        ('Whole Body 3', 'strength'),
        ('Whole Body 4', 'strength'),
        ('Whole Body 5', 'strength'),
        ('Whole Body 6', 'strength'),
        ('Push A', 'strength'),
        ('Pull A', 'strength'),
        ('Legs A', 'strength'),
        ('Push B', 'strength'),
        ('Pull B', 'strength'),
        ('Legs B', 'strength'),
        ('Walk', 'cardio'),
        ('5k', 'cardio'),
        ('HIIT', 'cardio'),
        ('Yoga', 'mobility'),
        ('Flexibility Routine', 'mobility'),